TRUTH = (
    "Pernah goshting?",
    "Pernah PUP di celana?",
    "Ngga bisa move on dari siapa, kenapa?",
    "Pernah bolos sekolah demi dia?",
    "Goshting atau Nge-goshting",
    "Paling takut kehilangan siapa sekarang?",
    "Lagi deket sama siapa?",
    "Pilih Real tapi badboy, atau virtual tapi goodboy?",
    "Mandang fisik ga?",
    "Pernah selingkuh?",
    "Sering bohong sama pacar tentang apa?",
    "Kriteria pasangan?",
    "Paling takut sama apa?",
    "Jatuh cinta terdalam sama siapa?",
    "Kapan terakhir minta pap sama pacar?",
    "Pernah bohong soal umur divirtual?",
    "Masih suka stalking mantan?",
    "Paling Phobia sama apa?",
    "Cerita pacaran paling sedih sama siapa?",
    "Alergi sama apa?",
    "Pilih virtual apa real?",
    "Kapan terakhir kali kamu berbohong sama orang tua?",
    "Apa kebohongan yang kamu lakukan sama orang tua yang terparah?",
    "Kapan terakhir kali kamu bohong sama kami?",
    "Apa aib yang kamu sembunyikan dari kami?",
    "Kapan terakhir kali kamu kelaparan?",
    "Berapa sisa saldo atm kamu?",
    "Berapa sisa uang di dompetmu?",
    "Mengapa kamu putus dengan mantanmu?",
    "Berapa banyak mantan kamu?",
    "Apa saja yang sudah kamu lakukan dengan mantanmu?",
    "Siapa cinta pertamamu?",
    "Siapa first datemu?",
    "Kemana kamu diajak jalan pertama kali?",
    "siapa mantan yang paling kamu sayang?",
    "siapa mantan yang paling kamu benci?",
    "siapa mantan terindah menurut kamu?",
    "siapa mantan yang brengsek?",
    "siapa mantan yang kere?",
    "siapa teman yang paling kamu benci diantara kita?",
    "siapa teman yang paling kamu sayang diantara kita?",
    "siapa teman yang paling pelit diantara kita?",
    "siapa teman yang paling judes diantara kita?",
    "siapa teman yang paling polos diantara kita?",
    "siapa crush kamu diantara kita?",
    "kepada siapa kamu pernah memendam perasaan?",
    "siapa yang pernah buat kamu menangis diantara kita?",
    "siapa yang pernah buat kamu bahagia sekali diantara kita?",
    "apakah kamu pernah jatu cinta sama sahabat sendiri?",
    "apakah kamu pernah dipinjam uang oleh teman kita?",
    "hal paling memalukan apa yang pernah terjadi di hidupmu?",
    "apa hal paling kejam yang pernah kamu lakukan dalam hidupmu?",
    "siapa yang kamu harapkan hadir disini sekarang?",
    "Apakah kamu pernah mencuri?",
    "hal paling menjijikkan yang pernah kamu lakukan apa?",
    "musik yang paling tidak kamu sukai?",
    "hal memalukan bersama gebetan yang pernah terjadi?",
    "siapa yang paling jelek diantara kita?",
    "Film paling bikin kamu baper ketika nonton bersama crush kamu apa?",
    "hal paling manis yang kamu lalui bersama kita?",
)

DARE = (
    "Kirim photo Aib disini, sekarang!",
    "Kirim SS chat tele",
    "PC owner dan bilang i love you",
    "Tag mantan",
    "Chat random member group dan bilang kamu kangen",
    "Kirim SS galeri",
    "Bilang ke mantan kamu mau balikan!",
    "Tembak orang yg chat diatas kamu",
    "PAP kuku jari tengah",
    "Naik OS dan bilang aku sayang kamu ke sembarang orang",
    "Nyanyi lagu galau di OS",
    "Kirim PAP muka jelek",
    "PC @kang_keong17",
    "SS wallpaper hp, wa dan tele",
    "Kirim VN desah",
    "SS Chat pacar",
    "Tag admin yg kamu suka",
    "Pap isi dompet",
    "SS chat BOT anon",
    "Bilang kangen ke mantan",
    "Tag admin yg kamu benci",
    "PAP lagi merem",
    "Bilang makasih ke semua admin",
    "Send nomer Whatsapp",
    "VN ketawa",
    "VN nangis",
    "Sikut Challenge",
    "SS fyp tiktok",
    "Kirim foto masih kecil",
    "SS keranjang Olshop",
    "Spil umur",
    "Tag orang yg paling kamu benci di sini",
    "Spill nama asli",
    "SS chat di putusin",
    "Nyalain tethering tanpa pass selama 1 jam",
    "Kirim selfi terakhir.",
    "Kirim selfi ke salah satu admin.",
    "SS DM instagram",
    "SS Search panel Instagram.",
    "SS Inbok FB",
    "SS chat whatsapp.",
    "SS chat gibah",
    "SS chat sama mama/papa.",
    "nyanyi via vn/os. 🎤",
    "Spill akun instagram.",
    "Tembak gebetan. ❤️",
    "Pasang PP foto gebetan.",
    "Pasang PP yg sama kaya salah satu admin, tag!.",
    "Pasang PP foto mantan.",
    "Ceritain cerita paling sedih kamu.",
)
